name: volunteering_app
description: A Flutter app for volunteering
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  webview_flutter: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter_lints: ^2.0.0

